name: cpc2
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.3.0
  - torchvision
  - cudatoolkit=9.2
  - cython
  - nose
  - numpy>=1.20
  - psutil
  - pip
  - pysoundfile
  - tqdm
  - joblib
  - openblas-devel
  - librosa
  - pandas=1.2.4
  - sox
  - pip:
    - progressbar2
    - threadpoolctl==3.1.0
    - torchaudio
    - torch-audiomentations
    - transformers
