name: cpc2
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pytorch=1.6.0
  - torchvision
  - cudatoolkit=10.2
  - psutil
  - pip
  - openblas-devel
  - tqdm
  - nose
  - cython
  - sox
  - pip:
    - progressbar2
    - matplotlib
    - torchaudio==0.6.0
